apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: my-web

  template:
    metadata:
      labels:
        app: my-web

    spec:
      containers:
      - name: my-web-container
        image: my-web-app:latest
        imagePullPolicy: Never

        env:
        - name: STUDENT_NAME
          value: "Lakshmi Priya K S"

        ports:
        - containerPort: 80
